# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jta6dkjj661TO_x5N7IHVjsEU9ez1NH-
"""

# =========================================================
# CELL 1: Install dependencies
# =========================================================
!pip -q install -U pandas==2.2.2
!pip -q install -U "transformers==4.56.2" "accelerate==0.34.2" "datasets==2.21.0" sentencepiece openpyxl sentence-transformers

# =========================================================
# CELL 2: Imports & seeds
# =========================================================
import os
import re
import gc
import json
import shutil
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from datasets import Dataset
from transformers import AutoTokenizer
from sentence_transformers import SentenceTransformer

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("pandas:", pd.__version__)
print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())

# =========================================================
# CELL 3: Load data
# =========================================================
BR_FILE = "/content/BUSINESS Requirement.xlsx"
SR_FILE = "/content/System_Requirements.xlsx"

br = pd.read_excel(BR_FILE)
sr = pd.read_excel(SR_FILE)

print("BR shape:", br.shape)
print("SR shape:", sr.shape)
display(br.head())
display(sr.head())

# =========================================================
# CELL 4: Generate SR text + build dataset
# =========================================================
def generate_sr_text(row):
    task_type = str(row["Task_Type"]).strip()
    task_subtype = str(row["Task_Subtype"]).strip()
    return f"The system shall support {task_subtype} as part of {task_type}."

sr["System_Requirement_Text"] = sr.apply(generate_sr_text, axis=1)
display(sr[["BR_ID", "SystemReq_ID", "Task_Type", "Task_Subtype", "System_Requirement_Text"]].head())

dataset = []

for br_id, grp in sr.groupby("BR_ID"):
    br_rows = br[br["BR_ID"] == br_id]
    if br_rows.empty:
        continue

    br_row = br_rows.iloc[0]
    br_json = {
        "br_id":       str(br_id),
        "text":        str(br_row["Business_Requirement_Text"]),
        "task_type":   str(br_row["Primary_Task_Type"])    if "Primary_Task_Type"    in br.columns else "",
        "task_subtype":str(br_row["Primary_Task_Subtype"]) if "Primary_Task_Subtype" in br.columns else "",
    }

    grp2 = grp.head(2)

    # ✅ FIX: skip BRs with less than 2 SRs so model always learns 2 SRs
    if len(grp2) < 2:
        continue

    sr_list = []
    for _, r in grp2.iterrows():
        sr_list.append({
            "sr_id":               str(r["SystemReq_ID"]),
            "text":                str(r["System_Requirement_Text"]),
            "required_experience": str(r["Required_Experience_Level"]),
            "uncertainty":         float(r["Uncertainty_PerReq_0_1"]),
        })

    full = {"business_requirement": br_json, "system_requirements": sr_list}
    inp  = {"business_requirement": br_json}

    dataset.append({
        "input":  json.dumps(inp,  ensure_ascii=False),
        "target": json.dumps(full, ensure_ascii=False)
    })

random.shuffle(dataset)
print("Examples:", len(dataset))
print("Sample input:\n",  dataset[0]["input"][:300])
print("\nSample target:\n", dataset[0]["target"][:500])

print("Dataset size after filtering:", len(dataset))

# =========================================================
# CELL 5: Train/val split + tokenize
# =========================================================
split    = int(0.9 * len(dataset))
train_ds = Dataset.from_list(dataset[:split])
val_ds   = Dataset.from_list(dataset[split:])
print(train_ds)
print(val_ds)

model_name = "google/flan-t5-small"
tokenizer  = AutoTokenizer.from_pretrained(model_name)

max_in  = 512
max_out = 512

def preprocess(batch):
    # ✅ FIX: prompt explicitly demands EXACTLY 2 SRs
    prefix = (
        "Return ONLY valid JSON with EXACTLY 2 system requirements.\n"
        "Output must match this schema exactly:\n"
        '{"business_requirement":{"br_id":"","text":"","task_type":"","task_subtype":""},'
        '"system_requirements":['
        '{"sr_id":"","text":"","required_experience":"","uncertainty":0.0},'
        '{"sr_id":"","text":"","required_experience":"","uncertainty":0.0}'
        ']}\n\nINPUT:\n'
    )
    inputs = [prefix + x for x in batch["input"]]
    model_inputs          = tokenizer(inputs,                       max_length=max_in,  truncation=True)
    labels                = tokenizer(text_target=batch["target"],  max_length=max_out, truncation=True)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_tok = train_ds.map(preprocess, batched=True, remove_columns=train_ds.column_names)
val_tok   = val_ds.map(preprocess,   batched=True, remove_columns=val_ds.column_names)
print(train_tok)
print(val_tok)

lens = [
    sum(1 for x in ex["labels"] if x != tokenizer.pad_token_id)
    for ex in train_tok.select(range(min(50, len(train_tok))))
]
print("Avg non-pad label tokens:", float(np.mean(lens)))
print("Min non-pad label tokens:", int(np.min(lens)))
assert np.min(lens) > 5, "Labels look empty or too short"

# =========================================================
# CELL 6: Train
# =========================================================
import accelerate
from transformers import (
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)

if not hasattr(accelerate.Accelerator, "_patched"):
    _orig_unwrap = accelerate.Accelerator.unwrap_model
    def _patched_unwrap(self, model, **kwargs):
        return _orig_unwrap(self, model)
    accelerate.Accelerator.unwrap_model = _patched_unwrap
    accelerate.Accelerator._patched = True

model    = AutoModelForSeq2SeqLM.from_pretrained(model_name)
collator = DataCollatorForSeq2Seq(tokenizer, model=model)

args = Seq2SeqTrainingArguments(
    output_dir="br_to_full_json",
    learning_rate=1e-4,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=5,
    predict_with_generate=False,
    fp16=False,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=collator,
    processing_class=tokenizer,
)

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

trainer.train()

# =========================================================
# CELL 7: Save model + plot loss
# =========================================================
from google.colab import files

FINAL_MODEL_DIR = "flan_t5_br_to_sr"
trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)
print("Saved to:", FINAL_MODEL_DIR)
print(os.listdir(FINAL_MODEL_DIR))

shutil.make_archive("flan_t5_br_to_sr", "zip", FINAL_MODEL_DIR)
print("Created zip: flan_t5_br_to_sr.zip")
files.download("flan_t5_br_to_sr.zip")

logs       = trainer.state.log_history
train_steps = [x["step"] for x in logs if "loss" in x]
train_loss  = [x["loss"] for x in logs if "loss" in x]
eval_steps  = [x["step"] for x in logs if "eval_loss" in x]
eval_loss   = [x["eval_loss"] for x in logs if "eval_loss" in x]

plt.figure(figsize=(8, 5))
if train_steps: plt.plot(train_steps, train_loss, label="Train Loss")
if eval_steps:  plt.plot(eval_steps,  eval_loss,  label="Validation Loss")
plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.savefig("model1_loss.png", bbox_inches="tight")
plt.show()
files.download("model1_loss.png")

metrics = trainer.evaluate()
print(metrics)

# =========================================================
# CELL 8: Define generate_raw + parse_model_output
# =========================================================
def generate_raw(br_json_dict):
    # ✅ FIX: prompt demands EXACTLY 2 SRs + more tokens
    prompt = (
        "Return ONLY valid JSON with EXACTLY 2 system requirements.\n"
        "Output must match this schema exactly:\n"
        '{"business_requirement":{"br_id":"","text":"","task_type":"","task_subtype":""},'
        '"system_requirements":['
        '{"sr_id":"","text":"","required_experience":"","uncertainty":0.0},'
        '{"sr_id":"","text":"","required_experience":"","uncertainty":0.0}'
        ']}\n\n'
        "INPUT:\n"
        + json.dumps({"business_requirement": br_json_dict}, ensure_ascii=False)
    )
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(model.device)

    out = model.generate(
        **inputs,
        max_new_tokens=600,  # ✅ FIX: increased from 450
        num_beams=4
    )
    return tokenizer.decode(out[0], skip_special_tokens=True)


def _extract_json_array_after_key(raw: str, key: str) -> str:
    m = re.search(rf'"{re.escape(key)}"\s*:\s*\[', raw)
    if not m:
        return ""
    start = m.end() - 1
    i, depth, in_str, esc = start, 0, False, False
    while i < len(raw):
        ch = raw[i]
        if in_str:
            if esc:               esc = False
            elif ch == '\\':      esc = True
            elif ch == '"':       in_str = False
        else:
            if   ch == '"':       in_str = True
            elif ch == '[':       depth += 1
            elif ch == ']':
                depth -= 1
                if depth == 0:    return raw[start:i+1]
        i += 1
    return ""


def parse_model_output(raw_text: str):
    raw = raw_text.strip()

    def grab_str(key):
        m = re.search(rf'"{key}"\s*:\s*"([^"]*)"', raw)
        return m.group(1) if m else ""

    br = {
        "br_id":        grab_str("br_id"),
        "text":         grab_str("text"),
        "task_type":    grab_str("task_type"),
        "task_subtype": grab_str("task_subtype"),
    }

    # Try robust bracket-balanced extraction first
    sr_array_text = _extract_json_array_after_key(raw, "system_requirements")
    srs = []

    if sr_array_text:
        try:
            sr_list = json.loads(sr_array_text)
            for item in (sr_list if isinstance(sr_list, list) else []):
                if not isinstance(item, dict):
                    continue
                srs.append({
                    "sr_id":               str(item.get("sr_id", "")),
                    "text":                str(item.get("text", "")),
                    "required_experience": str(item.get("required_experience", "")),
                    "uncertainty":         float(item.get("uncertainty", 0.0)) if item.get("uncertainty", "") != "" else 0.0
                })
        except Exception:
            # Fallback: regex extraction
            sr_ids   = re.findall(r'"sr_id"\s*:\s*"((?:\\.|[^"\\])*)"',               sr_array_text, re.S)
            sr_texts = re.findall(r'"text"\s*:\s*"((?:\\.|[^"\\])*)"',                sr_array_text, re.S)
            req_exps = re.findall(r'"required_experience"\s*:\s*"((?:\\.|[^"\\])*)"', sr_array_text, re.S)
            uncs     = re.findall(r'"uncertainty"\s*:\s*([0-9]*\.?[0-9]+)',            sr_array_text)
            n = max(len(sr_ids), len(sr_texts), len(req_exps), len(uncs), 0)
            for i in range(n):
                srs.append({
                    "sr_id":               sr_ids[i]   if i < len(sr_ids)   else "",
                    "text":                sr_texts[i]  if i < len(sr_texts) else "",
                    "required_experience": req_exps[i]  if i < len(req_exps) else "",
                    "uncertainty":         float(uncs[i]) if i < len(uncs)  else 0.0
                })

    return {"business_requirement": br, "system_requirements": srs}

# =========================================================
# CELL 9: Test inference + save sample outputs
# =========================================================
br_json = json.loads(train_ds[0]["input"])["business_requirement"]
raw     = generate_raw(br_json)
fixed   = parse_model_output(raw)

print("RAW:\n", raw)
print(f"\nNumber of SRs generated: {len(fixed['system_requirements'])}")
print("\nFIXED:\n", json.dumps(fixed, indent=2, ensure_ascii=False))

with open("model1_sample_raw.txt",   "w", encoding="utf-8") as f: f.write(raw)
with open("model1_sample_fixed.json","w", encoding="utf-8") as f: json.dump(fixed, f, indent=2, ensure_ascii=False)

files.download("model1_sample_raw.txt")
files.download("model1_sample_fixed.json")

# =========================================================
# CELL 10: Generate SR embeddings for ALL BRs in train_ds
# =========================================================
emb_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
print("Embedding dim:", emb_model.get_sentence_embedding_dimension())

all_sr_texts = []
all_sr_ids   = []

LIMIT = len(train_ds)

for i in range(LIMIT):
    if i % 20 == 0:
        print(f"Generating SRs for BR {i}/{LIMIT}")

    br_json = json.loads(train_ds[i]["input"])["business_requirement"]
    raw     = generate_raw(br_json)
    fixed   = parse_model_output(raw)

    for sr_item in fixed.get("system_requirements", []):
        txt = sr_item.get("text", "").strip()
        if txt:
            all_sr_texts.append(txt)
            all_sr_ids.append(sr_item.get("sr_id", ""))

print("Total SRs collected:", len(all_sr_texts))

embeddings = emb_model.encode(
    all_sr_texts,
    batch_size=64,
    normalize_embeddings=True,
    show_progress_bar=True
)
print("Embeddings shape:", embeddings.shape)

# =========================================================
# CELL 11: Save task vectors (TaskID + t0..tN)
# =========================================================
rows_task = []
for i, vec in enumerate(embeddings):
    row = {"TaskID": all_sr_ids[i]}
    for k, v in enumerate(vec):
        row[f"t{k}"] = float(v)
    rows_task.append(row)

df_task = pd.DataFrame(rows_task)
df_task.to_csv("tasks_vectors_FULL.csv", index=False)
print("Saved tasks_vectors_FULL.csv, shape:", df_task.shape)
files.download("tasks_vectors_FULL.csv")

# =========================================================
# CELL 12: Save subtask vectors (Sub_Task_ID + v0..vN)
# =========================================================
rows_sub = []
for i, vec in enumerate(embeddings):
    row = {"Sub_Task_ID": all_sr_ids[i]}
    for k, v in enumerate(vec):
        row[f"v{k}"] = float(v)
    rows_sub.append(row)

df_sub = pd.DataFrame(rows_sub)
df_sub.to_csv("subtask_vectors.csv", index=False)
print("Saved subtask_vectors.csv, shape:", df_sub.shape)
files.download("subtask_vectors.csv")

# =========================================================
# CELL 13: Build subtask vectors from SR Excel (by SubtaskID)
# =========================================================
sr_raw = pd.read_excel(SR_FILE)

if "System_Requirement_Text" not in sr_raw.columns:
    sr_raw["System_Requirement_Text"] = sr_raw.apply(generate_sr_text, axis=1)
else:
    sr_raw["System_Requirement_Text"] = sr_raw["System_Requirement_Text"].fillna("").astype(str).str.strip()

def sr_id_to_int(sr_id):
    if sr_id is None: return None
    s = str(sr_id).strip()
    if not s: return None
    m = re.search(r'(\d+)\D+(\d+)\s*$', s)
    if m:
        return int(m.group(1)) * 100 + int(m.group(2))
    digits = re.findall(r'\d+', s)
    return int("".join(digits)) if digits else None

candidate_cols = ["SubtaskID", "Sub_Task_ID", "Subtask_ID"]
existing = next((c for c in candidate_cols if c in sr_raw.columns), None)

if existing:
    sr_raw["SubtaskID"] = pd.to_numeric(sr_raw[existing], errors="coerce").astype("Int64")
else:
    id_col = next((c for c in sr_raw.columns if "id" in c.lower() and "system" in c.lower()), None)
    if id_col is None:
        raise ValueError("Couldn't find a System Requirement ID column.")
    sr_raw["SubtaskID"] = sr_raw[id_col].apply(sr_id_to_int).astype("Int64")

sr_raw = sr_raw.dropna(subset=["SubtaskID"]).copy()
sr_raw["SubtaskID"] = sr_raw["SubtaskID"].astype(int)
sr_raw["System_Requirement_Text"] = sr_raw["System_Requirement_Text"].fillna("").astype(str).str.strip()
sr_raw = sr_raw[sr_raw["System_Requirement_Text"] != ""].copy()

print("SR rows after cleaning:", len(sr_raw))
print("Unique SubtaskIDs:", sr_raw["SubtaskID"].nunique())

emb_excel = emb_model.encode(
    sr_raw["System_Requirement_Text"].tolist(),
    batch_size=128,
    normalize_embeddings=True,
    show_progress_bar=True
).astype(np.float32)

D = emb_excel.shape[1]
vec_cols = [f"s{i}" for i in range(D)]
df_vec   = pd.DataFrame(emb_excel, columns=vec_cols)
df_vec.insert(0, "SubtaskID", sr_raw["SubtaskID"].values)

df_vec = df_vec.groupby("SubtaskID", as_index=False).mean()
df_vec = df_vec.replace([np.inf, -np.inf], 0.0).fillna(0.0)

assert df_vec["SubtaskID"].is_unique,       "SubtaskID is not unique!"
assert df_vec.isna().sum().sum() == 0,      "NaN detected!"

df_vec.to_csv("subtask_vectors_by_id.csv", index=False)
print("Saved subtask_vectors_by_id.csv, shape:", df_vec.shape)
files.download("subtask_vectors_by_id.csv")

print("\n✅ All done! Downloaded files:")
print("  - flan_t5_br_to_sr.zip   (trained model)")
print("  - model1_loss.png        (loss plot)")
print("  - model1_sample_raw.txt  (sample raw output)")
print("  - model1_sample_fixed.json (sample parsed output)")
print("  - tasks_vectors_FULL.csv")
print("  - subtask_vectors.csv")
print("  - subtask_vectors_by_id.csv")