# -*- coding: utf-8 -*-
"""GAT2_criticality score_new_neww.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmTA8lsbHfFSl0CpHvpS6bxVFvBJNYlW
"""

# ── INSTALL ───────────────────────────────────────────────────
!pip -q install tensorflow pandas numpy scikit-learn matplotlib networkx

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import networkx as nx
import sys
sys.setrecursionlimit(10000)

from sklearn.metrics import mean_absolute_error, mean_squared_error

print("TF version:", tf.__version__)

# =========================================================
# STEP 1: LOAD DATA
# =========================================================
PREDICTIONS_PATH  = "/content/Subtask_Direct_Relationships_WITH_PREDICTIONS.csv"
GROUND_TRUTH_PATH = "/content/GAT2_Criticality_GroundTruth.csv"

df_pred = pd.read_csv(PREDICTIONS_PATH)
df_gt   = pd.read_csv(GROUND_TRUTH_PATH)

df_pred['Subtask_A'] = df_pred['Subtask_A'].str.strip()
df_pred['Subtask_B'] = df_pred['Subtask_B'].str.strip()
df_gt['Subtask']     = df_gt['Subtask'].str.strip()

print("Predictions shape:", df_pred.shape)
print("Ground truth shape:", df_gt.shape)
print("\nGround truth sample:")
print(df_gt.sort_values('criticality_normalized', ascending=False).head(5).to_string(index=False))

# =========================================================
# STEP 2: BUILD DAG (DFS cycle breaking)
# =========================================================
df_edges = df_pred[df_pred['Predicted_Relationship'] != 'NO_RELATION'].copy()

G = nx.DiGraph()
for _, row in df_edges.iterrows():
    G.add_edge(row['Subtask_A'], row['Subtask_B'])

print(f"\nBefore cycle breaking: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")
print("Is DAG?", nx.is_directed_acyclic_graph(G))

# Simple DFS cycle breaking
def dfs_break_cycles(G):
    visited   = set()
    rec_stack = set()
    edges_to_remove = []

    def dfs(node):
        visited.add(node)
        rec_stack.add(node)
        for nb in list(G.successors(node)):
            if nb not in visited:
                dfs(nb)
            elif nb in rec_stack:
                edges_to_remove.append((node, nb))
        rec_stack.discard(node)

    for node in list(G.nodes()):
        if node not in visited:
            dfs(node)

    for u, v in edges_to_remove:
        if G.has_edge(u, v):
            G.remove_edge(u, v)
    return edges_to_remove

removed = dfs_break_cycles(G)
print(f"Edges removed (cycles): {len(removed)}")
print(f"After cycle breaking:   {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")
print("Is DAG now?", nx.is_directed_acyclic_graph(G))

# =========================================================
# STEP 3: BUILD NODE LIST + FEATURES
# =========================================================
# Use nodes from ground truth (these have labels)
gt_nodes = df_gt['Subtask'].tolist()

# Add any nodes from graph not in ground truth (fill with 0)
graph_nodes = set(G.nodes())
all_nodes   = sorted(set(gt_nodes) | graph_nodes)

node2idx = {n: i for i, n in enumerate(all_nodes)}
N = len(all_nodes)
print(f"\nTotal nodes: {N}")

# Ground truth labels (criticality_normalized)
gt_lookup = dict(zip(df_gt['Subtask'], df_gt['criticality_normalized']))
y_all = np.array([gt_lookup.get(n, 0.0) for n in all_nodes], dtype=np.float32)

# Node features: in_degree, out_degree (normalized)
in_deg  = np.array([G.in_degree(n)  if n in G else 0 for n in all_nodes], dtype=np.float32)
out_deg = np.array([G.out_degree(n) if n in G else 0 for n in all_nodes], dtype=np.float32)

# Normalize degrees
in_deg_norm  = in_deg  / (in_deg.max()  + 1e-8)
out_deg_norm = out_deg / (out_deg.max() + 1e-8)

# Node feature matrix: [in_degree_norm, out_degree_norm]
is_source    = (in_deg == 0).astype(np.float32)
is_sink      = (out_deg == 0).astype(np.float32)
total_degree = in_deg + out_deg
total_deg_norm = total_degree / (total_degree.max() + 1e-8)
degree_ratio = out_deg / (total_degree + 1e-8)

X = np.stack([
    in_deg_norm,
    out_deg_norm,
    is_source,
    is_sink,
    total_deg_norm,
    degree_ratio
], axis=1).astype(np.float32)
print("Node feature matrix shape:", X.shape)
print("Target (y) shape:", y_all.shape)
print(f"Target range: [{y_all.min():.4f}, {y_all.max():.4f}]")

# =========================================================
# STEP 4: BUILD EDGE INDEX
# =========================================================
src_list, dst_list = [], []
for u, v in G.edges():
    if u in node2idx and v in node2idx:
        src_list.append(node2idx[u])
        dst_list.append(node2idx[v])

edge_index = np.array([src_list, dst_list], dtype=np.int64)
print(f"\nEdge index shape: {edge_index.shape}")

# =========================================================
# STEP 5: TRAIN / VAL / TEST SPLIT
# =========================================================
# Only split nodes that have ground truth labels
gt_indices = [node2idx[n] for n in gt_nodes if n in node2idx]
gt_indices = np.array(gt_indices)

np.random.seed(42)
perm    = np.random.permutation(len(gt_indices))
n_train = int(0.70 * len(gt_indices))
n_val   = int(0.15 * len(gt_indices))

train_nodes = gt_indices[perm[:n_train]]
val_nodes   = gt_indices[perm[n_train:n_train + n_val]]
test_nodes  = gt_indices[perm[n_train + n_val:]]

train_mask = np.zeros(N, dtype=bool)
val_mask   = np.zeros(N, dtype=bool)
test_mask  = np.zeros(N, dtype=bool)

train_mask[train_nodes] = True
val_mask[val_nodes]     = True
test_mask[test_nodes]   = True

print(f"\nTrain: {train_mask.sum()} | Val: {val_mask.sum()} | Test: {test_mask.sum()}")

# =========================================================
# STEP 6: GAT LAYER (TensorFlow)
# =========================================================
class GATLayer(tf.keras.layers.Layer):

    def __init__(self, out_dim, num_heads=4, concat=True, negative_slope=0.2, **kwargs):
        super().__init__(**kwargs)
        self.out_dim        = out_dim
        self.num_heads      = num_heads
        self.concat         = concat
        self.negative_slope = negative_slope

    def build(self, input_shape):
        in_dim = input_shape[0][-1]
        self.W = [
            self.add_weight(shape=(in_dim, self.out_dim),
                            initializer="glorot_uniform", trainable=True)
            for _ in range(self.num_heads)
        ]
        self.a = self.add_weight(shape=(self.num_heads, 2 * self.out_dim),
                                 initializer="glorot_uniform", trainable=True)

    def call(self, inputs):
        X        = tf.cast(inputs[0], tf.float32)
        edge_idx = tf.cast(inputs[1], tf.int64)
        src, dst = edge_idx[0], edge_idx[1]
        N_nodes  = tf.shape(X)[0]
        outputs  = []

        for h in range(self.num_heads):
            Wh      = tf.matmul(X, self.W[h])
            Wh_src  = tf.gather(Wh, src)
            Wh_dst  = tf.gather(Wh, dst)
            e       = tf.nn.leaky_relu(
                          tf.reduce_sum(
                              tf.concat([Wh_dst, Wh_src], axis=1) * self.a[h],
                              axis=1),
                          alpha=self.negative_slope)
            alpha   = tf.exp(e)
            denom   = tf.math.unsorted_segment_sum(alpha, dst, num_segments=N_nodes)
            alpha_n = alpha / (tf.gather(denom, dst) + 1e-9)
            out     = tf.math.unsorted_segment_sum(
                          tf.expand_dims(alpha_n, 1) * Wh_src,
                          dst, num_segments=N_nodes)
            outputs.append(out)

        if self.concat:
            return tf.concat(outputs, axis=1)
        else:
            return tf.reduce_mean(tf.stack(outputs, axis=0), axis=0)

class GATModel(tf.keras.Model):
    def __init__(self, hidden_dim=64, num_heads=4, out_dim=32):
        super().__init__()
        self.gat1   = GATLayer(hidden_dim, num_heads=num_heads, concat=True)
        self.gat2   = GATLayer(out_dim, num_heads=2, concat=False)
        self.linear = tf.keras.layers.Dense(1, activation='sigmoid')


    def call(self, inputs, training=False):
        X, edge_idx = inputs
        h1  = tf.nn.elu(self.gat1([X, edge_idx]))
        h2  = tf.nn.elu(self.gat2([h1, edge_idx]))
        out = self.linear(h2)
        return out

# =========================================================
# STEP 8: TRAINING
# =========================================================
model     = GATModel(hidden_dim=64, num_heads=4, out_dim=32)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=1.0)

X_tf         = tf.cast(X, tf.float32)
edge_idx_tf  = tf.cast(edge_index, tf.int64)
y_tf         = tf.cast(y_all.reshape(-1, 1), tf.float32)
train_mask_tf = tf.cast(train_mask, tf.float32)
val_mask_tf   = tf.cast(val_mask,   tf.float32)
test_mask_tf  = tf.cast(test_mask,  tf.float32)

def masked_mse(y_true, y_pred, mask):
    mask   = tf.cast(mask, tf.float32)
    error  = tf.square(y_true - y_pred) * tf.expand_dims(mask, 1)
    return tf.reduce_sum(error) / (tf.reduce_sum(mask) + 1e-8)

@tf.function
def train_step():
    with tf.GradientTape() as tape:
        y_pred = model([X_tf, edge_idx_tf], training=True)
        loss   = masked_mse(y_tf, y_pred, train_mask_tf)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    return loss

@tf.function
def eval_step(mask):
    y_pred = model([X_tf, edge_idx_tf], training=False)
    return masked_mse(y_tf, y_pred, mask)

EPOCHS       = 700
best_val     = float('inf')
best_epoch   = 0
best_weights = None
train_losses, val_losses = [], []

for epoch in range(1, EPOCHS + 1):
    tr_loss  = train_step()
    val_loss = eval_step(val_mask_tf)

    train_losses.append(float(tr_loss))
    val_losses.append(float(val_loss))

    if float(val_loss) < best_val:
        best_val     = float(val_loss)
        best_epoch   = epoch
        best_weights = [v.numpy() for v in model.trainable_variables]

    if epoch % 50 == 0:
        print(f"Epoch {epoch:03d} | Train: {tr_loss:.6f} | Val: {val_loss:.6f} | Best Val: {best_val:.6f} @ {best_epoch}")

# Restore best weights
for var, w in zip(model.trainable_variables, best_weights):
    var.assign(w)
print(f"\nRestored best weights from epoch {best_epoch} (val={best_val:.6f})")

# =========================================================
# STEP 9: PLOT
# =========================================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(train_losses, label="Train Loss", linewidth=2)
axes[0].plot(val_losses,   label="Val Loss",   linewidth=2)
axes[0].axvline(x=best_epoch, color='gray', linestyle='--', label=f"Best epoch {best_epoch}")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("MSE Loss")
axes[0].set_title("Train vs Val Loss"); axes[0].legend(); axes[0].grid(True)

axes[1].plot(train_losses[20:], label="Train Loss", linewidth=2)
axes[1].plot(val_losses[20:],   label="Val Loss",   linewidth=2)
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("MSE Loss")
axes[1].set_title("Zoomed (After Epoch 20)"); axes[1].legend(); axes[1].grid(True)

plt.tight_layout()
plt.show()

# =========================================================
# STEP 10: TEST EVALUATION
# =========================================================
y_pred_all = model([X_tf, edge_idx_tf], training=False).numpy().reshape(-1)
y_true_np  = y_all[test_mask]
y_pred_np  = y_pred_all[test_mask]

mae  = mean_absolute_error(y_true_np, y_pred_np)
mse  = mean_squared_error(y_true_np, y_pred_np)
rmse = np.sqrt(mse)
ss_res = np.sum((y_true_np - y_pred_np) ** 2)
ss_tot = np.sum((y_true_np - np.mean(y_true_np)) ** 2)
r2     = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0

print("=" * 40)
print("         Test Metrics")
print("=" * 40)
print(f"MAE  = {mae:.6f}")
print(f"MSE  = {mse:.6f}")
print(f"RMSE = {rmse:.6f}")
print(f"R²   = {r2:.6f}")
print("=" * 40)

# =========================================================
# STEP 11: EXPORT PREDICTIONS CSV
# =========================================================
# Min-shift to ensure all values >= 0
min_val    = y_pred_all.min()
y_pred_shifted = y_pred_all + abs(min_val) if min_val < 0 else y_pred_all
y_pred_shifted = np.clip(y_pred_shifted, 0.0, 1.0)

export_df = pd.DataFrame({
    'Subtask'                     : all_nodes,
    'GAT_Predicted_Critical_Score': y_pred_all,
    'GAT_Predicted_Critical_Shifted': y_pred_shifted,
    'GroundTruth_Critical_Score'  : y_all,
    'In_Degree'                   : in_deg,
    'Out_Degree'                  : out_deg,
}).sort_values('GAT_Predicted_Critical_Score', ascending=False)

print("\nTop 10 predicted critical subtasks:")
print(export_df.head(10)[['Subtask','GAT_Predicted_Critical_Score','GroundTruth_Critical_Score']].to_string(index=False))

export_df.to_csv("/content/GAT2_CriticalPath_Predictions.csv", index=False)

# Shifted version (for GAT1)
export_df.to_csv("/content/GAT2_CriticalPath_Predictions_Shifted.csv", index=False)
print("\nSaved: GAT2_CriticalPath_Predictions.csv")
print("Saved: GAT2_CriticalPath_Predictions_Shifted.csv")

# =========================================================
# STEP 12: SAVE MODEL
# =========================================================
model.save("/content/GAT2_model.keras")
print("Saved: GAT2_model.keras")

from google.colab import files
files.download("/content/GAT2_CriticalPath_Predictions.csv")
files.download("/content/GAT2_CriticalPath_Predictions_Shifted.csv")
files.download("/content/GAT2_model.keras")