# -*- coding: utf-8 -*-
"""GAT_employee_assignment_newww.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tigIWLkv9HZGnnCY38gHPEXE3S6nHQOC
"""

#Cell 1
!pip -q install torch torch_geometric scipy -U

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from torch_geometric.nn import GATConv

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

EDGE_PATH = "/content/Normalized_edges.csv"
EMP_PATH  = "/content/emp_vectors_clean.csv"
SUB_PATH  = "/content/subtask_vectors_Final_by_v8_id.csv"

edges_df = pd.read_csv(EDGE_PATH)
emp_df   = pd.read_csv(EMP_PATH)
sub_df   = pd.read_csv(SUB_PATH)

print("edges:", edges_df.shape, "emp:", emp_df.shape, "sub:", sub_df.shape)
print("edges cols:", list(edges_df.columns))


#No experience
zero_mask = (edges_df["Avg Duration (Hours)"] == 0) & \
            (edges_df["Avg Defects"] == 0) & \
            (edges_df["Total Defects (Sub Task)"] == 0)

edges_df = edges_df[~zero_mask].copy().reset_index(drop=True)
print("After removing no-experience pairs:", edges_df.shape)

# Load GAT2 criticality features
GAT2_PATH = "/content/GAT2_CriticalPath_Predictions_Shifted.csv"
gat2_df = pd.read_csv(GAT2_PATH)

# Normalize names for merge
sub_df['_merge_key'] = sub_df['Sub Task'].str.strip().str.lower()
gat2_df['_merge_key'] = gat2_df['Subtask'].str.strip().str.lower()

# Merge GAT2 features into sub_df
sub_df = sub_df.merge(
    gat2_df[['_merge_key', 'GAT_Predicted_Critical_Score', 'In_Degree', 'Out_Degree']],
    on='_merge_key', how='left'
).drop(columns=['_merge_key'])

# Fill missing (3 subtasks) with 0
sub_df[['GAT_Predicted_Critical_Score', 'In_Degree', 'Out_Degree']] = \
    sub_df[['GAT_Predicted_Critical_Score', 'In_Degree', 'Out_Degree']].fillna(0)

# Normalize the 3 new features (using all subtasks as reference)
for col in ['GAT_Predicted_Critical_Score', 'In_Degree', 'Out_Degree']:
    mu_col = sub_df[col].mean()
    std_col = sub_df[col].std()
    sub_df[col] = (sub_df[col] - mu_col) / (std_col + 1e-8)

print("sub_df shape after GAT2 merge:", sub_df.shape)

#Cell 2
# employee nodes
emp_ids = sorted(emp_df["EmployeeID"].unique())
emp2idx = {e: i for i, e in enumerate(emp_ids)}

# subtask nodes
sub_ids = sorted(sub_df["SubtaskID_v8"].unique())
sub2idx = {s: i for i, s in enumerate(sub_ids)}

emp_feat_cols = [c for c in emp_df.columns if c != "EmployeeID"]
sub_feat_cols = [c for c in sub_df.columns if c.startswith("s")] + \
                ['GAT_Predicted_Critical_Score', 'In_Degree', 'Out_Degree']

X_emp = torch.tensor(
    emp_df.set_index("EmployeeID").loc[emp_ids][emp_feat_cols].values,
    dtype=torch.float32, device=device
)

X_sub = torch.tensor(
    sub_df.set_index("SubtaskID_v8").loc[sub_ids][sub_feat_cols].values,
    dtype=torch.float32, device=device
)

print("X_emp:", X_emp.shape)
print("X_sub:", X_sub.shape)

#Cell 3
# map edges to indices
edges_df["u"] = edges_df["Employee ID"].map(emp2idx)
edges_df["v"] = edges_df["Subtask ID"].map(sub2idx)

edges_df = edges_df.dropna(subset=["u", "v"]).copy()
edges_df["u"] = edges_df["u"].astype(int)
edges_df["v"] = edges_df["v"].astype(int)

u_all = torch.tensor(edges_df["u"].values, dtype=torch.long, device=device)
v_all = torch.tensor(edges_df["v"].values, dtype=torch.long, device=device)

edge_feat_cols = [
    "Avg Duration (Hours)",
    "Avg Defects",
    "Total Defects (Sub Task)"
]

for c in edge_feat_cols:
    edges_df[c] = pd.to_numeric(edges_df[c], errors="raise")

edge_attr_all = torch.tensor(
    edges_df[edge_feat_cols].values,
    dtype=torch.float32, device=device
)

print("Edges count:", u_all.numel())
print("Edge features:", edge_attr_all.shape)

#Cell 4
print("Before dropna:", edges_df.shape)
edges_df = edges_df.dropna(subset=["u", "v"]).copy()
print("After  dropna:", edges_df.shape)

#Cell 5
np.random.seed(42)

N = u_all.size(0)
perm = np.random.permutation(N)

n_train = int(0.70 * N)
n_val   = int(0.15 * N)

train_idx = perm[:n_train]
val_idx   = perm[n_train:n_train + n_val]
test_idx  = perm[n_train + n_val:]

train_idx_t = torch.tensor(train_idx, dtype=torch.long, device=device)
val_idx_t   = torch.tensor(val_idx, dtype=torch.long, device=device)
test_idx_t  = torch.tensor(test_idx, dtype=torch.long, device=device)

print("Split:", train_idx_t.numel(), val_idx_t.numel(), test_idx_t.numel())

# Standardize edge_attr for model input using TRAIN only
mu  = edge_attr_all[train_idx_t].mean(dim=0, keepdim=True)
std = edge_attr_all[train_idx_t].std(dim=0, keepdim=True).clamp_min(1e-6)

edge_attr_train_std = (edge_attr_all - mu) / std

#Cell 6
E = X_emp.size(0)

edge_index = torch.stack([
    torch.cat([u_all, v_all + E]),
    torch.cat([v_all + E, u_all])
], dim=0)

print("edge_index:", edge_index.shape)

#Cell 7
dur_all  = edges_df["Avg Duration (Hours)"].values.astype(np.float32)
avgd_all = edges_df["Avg Defects"].values.astype(np.float32)
tdef_all = edges_df["Total Defects (Sub Task)"].values.astype(np.float32)

def z_from_train(all_arr, train_idx):
    tr = all_arr[train_idx]
    mu = tr.mean()
    sd = tr.std()
    if sd < 1e-8:
        return np.zeros_like(all_arr, dtype=np.float32), float(mu), float(sd)
    return ((all_arr - mu) / sd).astype(np.float32), float(mu), float(sd)

z_dur_all,  dur_mu,  dur_sd  = z_from_train(dur_all,  train_idx)
z_avgd_all, avgd_mu, avgd_sd = z_from_train(avgd_all, train_idx)
z_tdef_all, tdef_mu, tdef_sd = z_from_train(tdef_all, train_idx)

print("Target z-score stats (train-only):")
print("dur  mu/sd:", dur_mu, dur_sd)
print("avgd mu/sd:", avgd_mu, avgd_sd)
print("tdef mu/sd:", tdef_mu, tdef_sd)

#build t_all ONCE here, shape [N, 3], no betas involved
t_all = torch.stack([
    torch.tensor(z_dur_all,  dtype=torch.float32, device=device),
    torch.tensor(z_avgd_all, dtype=torch.float32, device=device),
    torch.tensor(z_tdef_all, dtype=torch.float32, device=device)
], dim=1)

print("t_all shape:", t_all.shape)  # should be [70680, 3]

#Cell 8
class BipartiteGAT_EdgeFeat(nn.Module):
    def __init__(self, emp_in, sub_in, edge_in=3, hid=64, heads=4, dropout=0.2):
        super().__init__()
        self.emp_proj = nn.Linear(emp_in, hid)
        self.sub_proj = nn.Linear(sub_in, hid)

        self.gat1 = GATConv(hid, hid, heads=heads, concat=True, dropout=dropout)
        self.gat2 = GATConv(hid * heads, hid, heads=1, concat=False, dropout=dropout)

        self.scorer = nn.Sequential(
            nn.Linear(hid * 2 + edge_in, hid),
            nn.LeakyReLU(0.01),
            nn.Dropout(dropout),
            nn.Linear(hid, 3)
        )

    def forward(self, X_emp, X_sub, edge_index, u, v, edge_attr_std):
        E = X_emp.size(0)

        x = torch.zeros((E + X_sub.size(0), self.emp_proj.out_features), device=X_emp.device)
        x[:E] = self.emp_proj(X_emp)
        x[E:] = self.sub_proj(X_sub)

        x = self.gat1(x, edge_index)
        x = torch.relu(x)
        x = self.gat2(x, edge_index)

        zu = x[u]
        zv = x[v + E]

        return self.scorer(torch.cat([zu, zv, edge_attr_std], dim=1))


model = BipartiteGAT_EdgeFeat(
    emp_in=X_emp.size(1),
    sub_in=X_sub.size(1),
    edge_in=3
).to(device)

criterion = nn.SmoothL1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

print(model)

#Cell 9
max_epochs = 400
min_epochs = 15
patience = 15

best_val = float("inf")
pat = 0
best_state = None

train_losses, val_losses = [], []

for epoch in range(1, max_epochs + 1):

    # -------- train
    model.train()
    optimizer.zero_grad()

    pred_tr = model(
        X_emp, X_sub, edge_index,
        u_all[train_idx_t],
        v_all[train_idx_t],
        edge_attr_train_std[train_idx_t],
    )  # shape [N_train, 3]

    loss_tr = criterion(pred_tr, t_all[train_idx_t])

    loss_tr.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
    optimizer.step()

    # -------- val
    model.eval()
    with torch.no_grad():
        pred_va = model(
            X_emp, X_sub, edge_index,
            u_all[val_idx_t],
            v_all[val_idx_t],
            edge_attr_train_std[val_idx_t],
        )  # shape [N_val, 3]

        loss_va = criterion(pred_va, t_all[val_idx_t]).item()

    train_losses.append(float(loss_tr.item()))
    val_losses.append(float(loss_va))

    print(f"Epoch {epoch:03d} | Train {loss_tr.item():.4f} | Val {loss_va:.4f}")

    if loss_va < best_val:
        best_val = loss_va
        best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        pat = 0
    else:
        pat += 1
        if epoch >= min_epochs and pat >= patience:
            print(f"\nEarly stopping at epoch {epoch} (best val={best_val:.6f})")
            break

if best_state is None:
    raise RuntimeError("best_state is None. No best checkpoint was saved.")

model.load_state_dict({k: v.to(device) for k, v in best_state.items()})
model.eval()

print("Restored best model. Best val loss =", best_val)

#Cell 10
from sklearn.metrics import mean_absolute_error, mean_squared_error

model.eval()

with torch.no_grad():
    pred_te = model(
        X_emp, X_sub, edge_index,
        u_all[test_idx_t],
        v_all[test_idx_t],
        edge_attr_train_std[test_idx_t],
    )  # shape [N_test, 3]

    loss_te = criterion(pred_te, t_all[test_idx_t]).item()

all_preds   = pred_te.cpu().numpy()
all_targets = t_all[test_idx_t].cpu().numpy()

mae  = mean_absolute_error(all_targets, all_preds)
mse  = mean_squared_error(all_targets, all_preds)
rmse = np.sqrt(mse)

print(f"Test Loss: {loss_te:.6f}")
print(f"MAE  = {mae:.6f}")
print(f"MSE  = {mse:.6f}")
print(f"RMSE = {rmse:.6f}")

#Cell 11
plt.figure()
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("SmoothL1 Loss")
plt.title("Train/Val Loss")
plt.legend()
plt.grid(True)
plt.show()

plt.figure()
plt.axhline(y=loss_te, color='r', linestyle='--', label=f"Test Loss = {loss_te:.6f}")
plt.xlabel("Epoch")
plt.ylabel("SmoothL1 Loss")
plt.title("Test Loss")
plt.legend()
plt.grid(True)
plt.show()

#Cell 12
torch.save({
    "model_state_dict": model.state_dict(),
    "emp2idx": emp2idx,
    "sub2idx": sub2idx,
    "emp_ids": emp_ids,
    "sub_ids": sub_ids,
    "edge_mu": mu.detach().cpu(),
    "edge_std": std.detach().cpu(),
    "edge_feat_cols": edge_feat_cols,
    "sub_feat_cols": sub_feat_cols,
    "emp_feat_cols": emp_feat_cols,
    "target_z_train_stats": {
        "dur_mu": dur_mu, "dur_sd": dur_sd,
        "avgd_mu": avgd_mu, "avgd_sd": avgd_sd,
        "tdef_mu": tdef_mu, "tdef_sd": tdef_sd,
    }
}, "GAT_cost_model.pt")

print("Saved: GAT_cost_model.pt")

#Cell 13
!pip -q install ahpy

import ahpy

# ── STEP 1: AHP BETAS ─────────────────────────────────────
comparisons = {
    ('duration', 'avg_defects')    : 3,
    ('duration', 'total_defects')  : 5,
    ('avg_defects', 'total_defects'): 3,
}
criteria = ahpy.Compare('Criteria', comparisons, precision=4)
beta_1 = criteria.target_weights['duration']   # cost weight
beta_2 = criteria.target_weights['avg_defects'] # duration weight
beta_3 = criteria.target_weights['total_defects'] # risk weight

print(f"β1 (cost)     = {beta_1:.4f}")
print(f"β2 (duration) = {beta_2:.4f}")
print(f"β3 (risk)     = {beta_3:.4f}")
print(f"CR = {criteria.consistency_ratio:.4f}")

# ── STEP 2: EMPLOYEE RATES (from experience level) ────────
rate_map = {
    'Intern / Trainee'   : 10,
    'Junior Developer'   : 20,
    'Mid-Level Developer': 30,
    'Senior Developer'   : 40,
    'Lead Engineer'      : 50,
}

# Load model2 output → experience level per employee
df_model2 = pd.read_csv("/content/model2_output.csv")
emp_exp = df_model2.groupby('Employee ID')['Predicted_ExperienceLevel'].first().reset_index()
emp_rate = dict(zip(emp_exp['Employee ID'],
                    emp_exp['Predicted_ExperienceLevel'].map(rate_map)))

print("\nSample employee rates:")
for emp, rate in list(emp_rate.items())[:5]:
    print(f"  Employee {emp}: {rate} $/hr")

# ── STEP 3: LOAD RAW EDGES (non-normalized for cost calc) ─
df_raw = pd.read_csv("/content/Normalized_edges.csv")

# Remove zero-experience pairs
zero_mask = (df_raw["Avg Duration (Hours)"] == 0) & \
            (df_raw["Avg Defects"] == 0) & \
            (df_raw["Total Defects (Sub Task)"] == 0)
df_raw = df_raw[~zero_mask].copy().reset_index(drop=True)

# ── STEP 4: COMPUTE cost, duration, risk ──────────────────
# duration = Avg Duration (Hours) — already normalized in edges
# cost     = duration × rate(employee)
# risk     = Total Defects (Sub Task) — already normalized

df_raw['rate'] = df_raw['Employee ID'].map(emp_rate).fillna(10)

# cost = duration × rate → then normalize 0→1
df_raw['cost_raw'] = df_raw['Avg Duration (Hours)'] * df_raw['rate']

# Normalize cost, duration, risk to [0, 1]
def normalize_col(series):
    mn, mx = series.min(), series.max()
    if mx > mn:
        return (series - mn) / (mx - mn)
    return series * 0.0

df_raw['cost_norm']     = normalize_col(df_raw['cost_raw'])
df_raw['duration_norm'] = normalize_col(df_raw['Avg Duration (Hours)'])
df_raw['risk_norm']     = normalize_col(df_raw['Total Defects (Sub Task)'])

# ── STEP 5: COMPUTE SCORE = β1*cost + β2*duration + β3*risk
df_raw['score'] = (beta_1 * df_raw['cost_norm'] +
                   beta_2 * df_raw['duration_norm'] +
                   beta_3 * df_raw['risk_norm'])

print("\nSample scores:")
print(df_raw[['Employee ID','Subtask ID','cost_norm','duration_norm','risk_norm','score']].head(5).to_string())

# ── STEP 6: BUILD SCORE MATRIX ────────────────────────────
# score matrix: emp × sub (lower = better → min assignment)
all_emp_ids = sorted(df_raw['Employee ID'].unique())
all_sub_ids = sorted(df_raw['Subtask ID'].unique())

emp2idx_new = {e: i for i, e in enumerate(all_emp_ids)}
sub2idx_new = {s: i for i, s in enumerate(all_sub_ids)}

n_emp = len(all_emp_ids)
n_sub = len(all_sub_ids)

score_matrix = np.full((n_emp, n_sub), np.inf)

for _, row in df_raw.iterrows():
    ei = emp2idx_new[row['Employee ID']]
    si = sub2idx_new[row['Subtask ID']]
    if row['score'] < score_matrix[ei, si]:
        score_matrix[ei, si] = row['score']

print(f"\nScore matrix shape: {score_matrix.shape}")
print(f"Non-inf entries: {np.sum(~np.isinf(score_matrix))}")

# ── STEP 7: SORT SUBTASKS BY CRITICALITY (GAT2 output) ───
gat2_lookup = dict(zip(
    gat2_df['Subtask'].str.strip().str.lower(),
    gat2_df['GAT_Predicted_Critical_Score']
))

# Map subtask IDs to criticality scores
# Need subtask ID → subtask name mapping
df_sub_names = df_model2[['Sub Task']].drop_duplicates().reset_index(drop=True)
df_sub_names['Subtask ID'] = df_raw.groupby('Subtask ID').first().reset_index()['Subtask ID'].values[:len(df_sub_names)]

# Use sub_df which has SubtaskID_v8 and Sub Task name
sub_id_to_name = dict(zip(sub_df['SubtaskID_v8'], sub_df['Sub Task'].str.strip().str.lower()))

sub_criticality = {}
for sub_id in all_sub_ids:
    name = sub_id_to_name.get(sub_id, '').strip().lower()
    sub_criticality[sub_id] = gat2_lookup.get(name, 0.0)

sorted_subs = sorted(all_sub_ids,
                     key=lambda s: sub_criticality[s],
                     reverse=True)

print("\nTop 5 subtasks by criticality:")
for s in sorted_subs[:5]:
    print(f"  SubtaskID {s}: criticality={sub_criticality[s]:.4f}")

# ── STEP 8: PRIORITY-BASED SEQUENTIAL ASSIGNMENT ──────────
assigned_employees = set()
assignments = []

for sub_id in sorted_subs:
    si = sub2idx_new[sub_id]
    best_emp  = None
    best_score = np.inf

    for ei, emp_id in enumerate(all_emp_ids):
        if emp_id in assigned_employees:
            continue  # already assigned → skip (infinity mask)
        if score_matrix[ei, si] < best_score:
            best_score = score_matrix[ei, si]
            best_emp   = emp_id

    if best_emp is not None:
        assignments.append({
            'EmployeeID'  : best_emp,
            'SubtaskID'   : sub_id,
            'Score'       : best_score,
            'Criticality' : sub_criticality[sub_id]
        })
        assigned_employees.add(best_emp)

# ── STEP 9: SAVE & DISPLAY ────────────────────────────────
assignment_df = pd.DataFrame(assignments)
assignment_df.to_csv("optimal_assignments.csv", index=False)

print(f"\nTotal assignments: {len(assignment_df)}")
print(f"Employees assigned: {len(assigned_employees)}")
print("\nTop 10 assignments (by criticality):")
print(assignment_df.head(10).to_string(index=False))

from google.colab import files
files.download("optimal_assignments.csv")