# -*- coding: utf-8 -*-
"""classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16MChOT0RrSj6Kl_8kKCJ6mIpKfZ92AuK
"""

!pip -q install scikit-learn joblib openpyxl

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import joblib, json

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers

import os

# List files to verify paths if the error persists
print("Files in current directory:", os.listdir())

# Updated paths: Colab default is usually /content/ instead of /mnt/data/
labels_path = "Subtask_Relationship_Labels.xlsx"
direct_path = "Subtask_Direct_Relationships.xlsx"

try:
    df = pd.read_excel(labels_path)         # has Relationship
    df_pred = pd.read_excel(direct_path)    # pairs only

    print("Train data shape:", df.shape)
    print("Predict data shape:", df_pred.shape)
    display(df.head())
except FileNotFoundError as e:
    print(f"Error: {e}")
    print("Please ensure the Excel files are uploaded to the Colab file explorer on the left.")

# Basic cleanup
df["Subtask_A"] = df["Subtask_A"].astype(str).str.strip()
df["Subtask_B"] = df["Subtask_B"].astype(str).str.strip()
df["Relationship"] = df["Relationship"].astype(str).str.strip().str.upper()

# Build a single input text per row (order matters for FS/SF/etc.)
def make_pair_text(a, b):
    return f"SUBTASK_A: {a} [SEP] SUBTASK_B: {b}"

df["pair_text"] = df.apply(lambda r: make_pair_text(r["Subtask_A"], r["Subtask_B"]), axis=1)

print(df["Relationship"].value_counts())

classes = sorted(df["Relationship"].unique().tolist())
class_to_id = {c:i for i,c in enumerate(classes)}
id_to_class = {i:c for c,i in class_to_id.items()}

y = df["Relationship"].map(class_to_id).values.astype("int32")
X_text = df["pair_text"].values

print("Classes:", classes)

X_train_text, X_temp_text, y_train, y_temp = train_test_split(
    X_text, y, test_size=0.30, random_state=42, stratify=y
)

X_val_text, X_test_text, y_val, y_test = train_test_split(
    X_temp_text, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

print("Train/Val/Test:", len(X_train_text), len(X_val_text), len(X_test_text))

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1,2),
    max_features=20000,
    min_df=2
)

X_train = vectorizer.fit_transform(X_train_text)
X_val   = vectorizer.transform(X_val_text)
X_test  = vectorizer.transform(X_test_text)

# Keras needs dense arrays
X_train_dense = X_train.toarray().astype("float32")
X_val_dense   = X_val.toarray().astype("float32")
X_test_dense  = X_test.toarray().astype("float32")

print("Dense shapes:", X_train_dense.shape, X_val_dense.shape, X_test_dense.shape)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.arange(len(classes)),
    y=y_train
)
class_weight_dict = {i: float(w) for i, w in enumerate(class_weights)}
class_weight_dict

num_features = X_train_dense.shape[1]
num_classes  = len(classes)

l2_val = 1e-4        # Dr. Yehia: 0.0001
drop_val = 0.3       # Dr. Yehia: 0.3
lr = 3e-4            # reduced LR (vs default 1e-3)

model = keras.Sequential([
    layers.Input(shape=(num_features,)),

    layers.Dense(512, activation="relu", kernel_regularizer=regularizers.l2(l2_val)),
    layers.BatchNormalization(),
    layers.Dropout(drop_val),

    layers.Dense(256, activation="relu", kernel_regularizer=regularizers.l2(l2_val)),
    layers.BatchNormalization(),
    layers.Dropout(drop_val),

    layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(l2_val)),
    layers.Dropout(drop_val),

    layers.Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=lr),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss", patience=5, restore_best_weights=True
    ),
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6, verbose=1
    )
]

history = model.fit(
    X_train_dense, y_train,
    validation_data=(X_val_dense, y_val),
    epochs=50,
    batch_size=64,
    class_weight=class_weight_dict,
    callbacks=callbacks,
    verbose=1
)

test_loss, test_acc = model.evaluate(X_test_dense, y_test, verbose=0)
print("Test accuracy:", test_acc)

y_pred_probs = model.predict(X_test_dense, verbose=0)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=classes, digits=4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

import matplotlib.pyplot as plt

# history can be a History object or a dict
hist = history.history if hasattr(history, "history") else history

plt.figure()
plt.plot(hist["loss"], label="Train Loss")
plt.plot(hist["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.show()

plt.figure()
plt.plot(hist["accuracy"], label="Train Accuracy")
plt.plot(hist["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.show()

import os, json, joblib

# Colab-safe output folder
BASE_DIR = "/content/model_outputs"
os.makedirs(BASE_DIR, exist_ok=True)

out_model_path = os.path.join(BASE_DIR, "subtask_relation_dnn.keras")
out_vec_path   = os.path.join(BASE_DIR, "tfidf_vectorizer.joblib")
out_map_path   = os.path.join(BASE_DIR, "label_map.json")

# Save
model.save(out_model_path)
joblib.dump(vectorizer, out_vec_path)

with open(out_map_path, "w") as f:
    json.dump(
        {"classes": classes, "class_to_id": class_to_id, "id_to_class": id_to_class},
        f,
        indent=2
    )

print("Saved to:", BASE_DIR)
print("Model:", out_model_path)
print("Vectorizer:", out_vec_path)
print("Label map:", out_map_path)

from google.colab import files
import zipfile, os

with zipfile.ZipFile("classifier_artifacts.zip", "w") as z:
    for fname in os.listdir(BASE_DIR):
        z.write(os.path.join(BASE_DIR, fname), fname)

files.download("classifier_artifacts.zip")

import os
import numpy as np
import pandas as pd

# Make sure df_pred is loaded
direct_path = "/content/Subtask_Direct_Relationships.xlsx"  # change if your file name differs
df_pred = pd.read_excel(direct_path)

df_pred["Subtask_A"] = df_pred["Subtask_A"].astype(str).str.strip()
df_pred["Subtask_B"] = df_pred["Subtask_B"].astype(str).str.strip()

def make_pair_text(a, b):
    return f"SUBTASK_A: {a} [SEP] SUBTASK_B: {b}"

df_pred["pair_text"] = df_pred.apply(
    lambda r: make_pair_text(r["Subtask_A"], r["Subtask_B"]), axis=1
)

X_pred = vectorizer.transform(df_pred["pair_text"].values).toarray().astype("float32")

pred_probs = model.predict(X_pred, verbose=0)
pred_ids = np.argmax(pred_probs, axis=1)

# id_to_class must exist; if not, rebuild it from classes
if "id_to_class" not in globals():
    id_to_class = {i:c for i,c in enumerate(classes)}

df_pred["Predicted_Relationship"] = [id_to_class[i] for i in pred_ids]
df_pred["Confidence"] = np.max(pred_probs, axis=1)

csv_path = os.path.join("/content", "Subtask_Direct_Relationships_WITH_PREDICTIONS.csv")
df_pred.to_csv(csv_path, index=False)

csv_path

from google.colab import files
files.download(csv_path)