# -*- coding: utf-8 -*-
"""Experience Level NN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drVFB0yOEUsCB1ZVCWLsnn7p78avqmqI
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

import os
import pandas as pd

# Ensure the path is correct. If the file is in your Google Drive,
# the path usually starts with '/content/drive/MyDrive/'
file_path = "/content/Generated_Employee_Task_Assignments_v8_FIXED_ALL_EXPERIENCE (1).xlsx"

if os.path.exists(file_path):
    df = pd.read_excel(file_path)
    print("File loaded successfully.")
    df.head()
else:
    print(f"Error: The file was not found at {file_path}.")
    print("Please check if the file is uploaded to Colab or if the path to your Google Drive is correct.")

target_col = "Experience Level"
X = df.drop(columns=[target_col])
y = df[target_col]

X = df.drop(columns=[target_col])
y = df[target_col]

X = pd.get_dummies(X, drop_first=False)

import joblib
DNN_COLUMNS = list(X.columns)
joblib.dump(DNN_COLUMNS, "dnn_columns.joblib")
print(" Saved dnn_columns.joblib | #cols:", len(DNN_COLUMNS))

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_enc = le.fit_transform(y)

print("Classes:", le.classes_)

import joblib
joblib.dump(le, "dnn_label_encoder.joblib")
print("Saved dnn_label_encoder.joblib | classes:", list(le.classes_))

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

unique_classes, counts = np.unique(y_enc, return_counts=True)
classes_to_remove = unique_classes[counts == 1]

if len(classes_to_remove) > 0:
    print(f"Removing classes with only one sample from original data: {le.inverse_transform(classes_to_remove)}")
    mask = ~np.isin(y_enc, classes_to_remove)

    X_filtered = X[mask]
    y_filtered = y_enc[mask]
    print(f"Original samples: {len(y_enc)}, Samples after initial filtering: {len(y_filtered)}")
else:
    X_filtered = X
    y_filtered = y_enc

X_train, X_temp, y_train, y_temp = train_test_split(
    X_filtered, y_filtered, test_size=0.3, random_state=42, stratify=y_filtered
)

unique_classes_temp, counts_temp = np.unique(y_temp, return_counts=True)
classes_to_remove_temp = unique_classes_temp[counts_temp == 1]

if len(classes_to_remove_temp) > 0:
    print(f"Removing classes from X_temp, y_temp with only one sample: {le.inverse_transform(classes_to_remove_temp)}")
    mask_temp = ~np.isin(y_temp, classes_to_remove_temp)
    X_temp_filtered = X_temp[mask_temp]
    y_temp_filtered = y_temp[mask_temp]
    print(f"Original temp samples: {len(y_temp)}, Temp samples after filtering: {len(y_temp_filtered)}")
else:
    X_temp_filtered = X_temp
    y_temp_filtered = y_temp

X_val, X_test, y_val, y_test = train_test_split(
    X_temp_filtered, y_temp_filtered, test_size=0.5, random_state=42, stratify=y_temp_filtered
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
import joblib
joblib.dump(scaler, "dnn_scaler.joblib")
print("Saved dnn_scaler.joblib")
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

num_features = X_train.shape[1]
num_classes = len(np.unique(np.concatenate((y_train, y_val, y_test)))) # Use all sets to determine num_classes

print("Features:", num_features)
print("Classes:", num_classes)

# ── SAVE SCALER ───────────────────────────────────────────────────────
import joblib
joblib.dump(scaler, "dnn_scaler.joblib")
print("✅ Saved dnn_scaler.joblib")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.long)

X_val_t = torch.tensor(X_val, dtype=torch.float32)
y_val_t = torch.tensor(y_val, dtype=torch.long)

X_test_t = torch.tensor(X_test, dtype=torch.float32)
y_test_t = torch.tensor(y_test, dtype=torch.long)


train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=64, shuffle=True)
val_loader   = DataLoader(TensorDataset(X_val_t, y_val_t), batch_size=256, shuffle=False)
test_loader  = DataLoader(TensorDataset(X_test_t, y_test_t), batch_size=256, shuffle=False)

class DNN(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 16)   # <-- embeddings
        self.out = nn.Linear(16, num_classes)

    def forward(self, x, return_embedding=False):
        x = torch.relu(self.fc1(x))
        emb = torch.relu(self.fc2(x))

        if return_embedding:
            return emb

        return self.out(emb)

#class DNN(nn.Module):
    #def __init__(self, input_dim, num_classes):
        #super().__init__()
        #self.net = nn.Sequential(
            #nn.Linear(input_dim, 32),  # hidden layer 1
            #nn.ReLU(),

            #nn.Linear(32, 16),         # hidden layer 2
            #nn.ReLU(),

            #nn.Linear(16, num_classes) # output layer
        #)

    #def forward(self, x):
        #return self.net(x)


model = DNN(num_features, num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

train_loss_history = []
val_loss_history = []

for epoch in range(1, 16):

    model.train()
    batch_losses = []

    for xb, yb in train_loader:
        optimizer.zero_grad()
        logits = model(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step()
        batch_losses.append(loss.item())

    train_loss = np.mean(batch_losses)
    train_loss_history.append(train_loss)

    model.eval()
    val_losses = []

    with torch.no_grad():
        for xb, yb in val_loader:
            logits = model(xb)
            val_loss = criterion(logits, yb)
            val_losses.append(val_loss.item())

    val_loss = np.mean(val_losses)
    val_loss_history.append(val_loss)

    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Train loss: {train_loss:.4f} | Val loss: {val_loss:.4f}")

model.eval()
with torch.no_grad():
    test_preds = torch.argmax(model(X_test_t), dim=1)
    test_acc = (test_preds == y_test_t).float().mean().item()

print("FINAL TEST ACCURACY:", test_acc)

model.eval()

X_all = df.drop(columns=["Experience Level"])
X_all = pd.get_dummies(X_all, drop_first=False)

X_all = X_all.reindex(columns=X.columns, fill_value=0)

X_all_scaled = scaler.transform(X_all)

X_all_t = torch.tensor(X_all_scaled, dtype=torch.float32)


with torch.no_grad():
    embeddings = model(X_all_t, return_embedding=True).numpy()

#with torch.no_grad():
    #logits = model(X_all_t)
    #preds = torch.argmax(logits, dim=1)

#predicted_levels = le.inverse_transform(preds.numpy())

with torch.no_grad():
    logits = model(X_all_t)
    preds = torch.argmax(logits, dim=1)

predicted_levels = le.inverse_transform(preds.numpy())

df["Predicted_ExperienceLevel"] = predicted_levels
df.head()

output = df[[
    "Employee ID",
    "Task",
    "Sub Task",
    "Predicted_ExperienceLevel"
]]
output.head()

import matplotlib.pyplot as plt

plt.plot(train_loss_history, label="Training Loss")
plt.plot(val_loss_history, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

torch.save(model.state_dict(), "experience_dnn_weights.pth")
print(" Saved experience_dnn_weights.pth")

!zip -r dnn_artifacts.zip experience_dnn_weights.pth dnn_columns.joblib dnn_scaler.joblib dnn_label_encoder.joblib

from google.colab import files
files.download("dnn_artifacts.zip")

model.load_state_dict(torch.load("experience_dnn_weights.pth"))
model.eval()

df["Predicted_ExperienceLevel"] = predicted_levels